repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        language: system
        entry: isort
        types: [python]

      - id: black
        name: black
        language: system
        entry: black
        types: [python]

      - id: trailing-whitespace
        name: trailing-whitespace
        language: system
        entry: trailing-whitespace-fixer
        types: [python]
        exclude: __main__\.py

      - id: end-of-file-fixer
        name: end-of-file-fixer
        language: system
        entry: end-of-file-fixer
        types: [python]

      - id: mixed-line-ending
        name: mixed-line-ending
        language: system
        entry: mixed-line-ending
        types: [python]
        args: ["--fix=lf"]

      - id: fix-encoding-pragma
        name: fix-encoding-pragma
        language: system
        entry: fix-encoding-pragma
        types: [python]
        args: ["--remove"]

      - id: check-case-conflict
        name: check-case-conflict
        language: system
        entry: check-case-conflict
        types: [python]

      - id: check-docstring-first
        name: check-docstring-first
        language: system
        entry: check-docstring-first
        types: [python]
        exclude: (a2c|actorch/envs/utils|algorithm|distributed_trainable|network|reinforce|version)\.py

      - id: check-merge-conflict
        name: check-merge-conflict
        language: system
        entry: check-merge-conflict
        types: [file]

      - id: flake8
        name: flake8 except __init__.py
        language: system
        entry: flake8
        types: [python]
        exclude: examples|(/__init__|__main__)\.py$

      - id: flake8
        name: flake8 only __init__.py
        language: system
        entry: flake8
        types: [python]
        # Ignore unused imports in __init__.py
        args: ["--extend-ignore=F401"]
        files: /__init__\.py$

      - id: mypy
        name: mypy
        language: system
        entry: mypy
        types: [python]
        exclude: (conf\.py|setup\.py|^tests/)

      - id: pytest
        name: pytest
        language: system
        entry: pytest
        types: [python]
        files: ^test
