channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2020.6.24
  - certifi=2020.6.20
  - cpuonly=1.0
  - icc_rt=2019.0.0
  - intel-openmp=2020.1
  - libuv=1.40.0
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - ninja=1.10.0
  - openssl=1.1.1g
  - pip=20.2.2
  - python=3.8.5
  - pytorch=1.12.0
  - pytorch-mutex=1.0
  - setuptools=49.6.0
  - sqlite=3.32.3
  - tk=8.6.10
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wheel=0.34.2
  - wincertstore=0.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - absl-py==0.9.0
    - aiohttp==3.6.2
    - aiohttp-cors==0.7.0
    - aioredis==1.3.1
    - alabaster==0.7.12
    - appdirs==1.4.4
    - astroid==2.4.2
    - async-timeout==3.0.1
    - atomicwrites==1.4.0
    - attrs==19.3.0
    - Babel==2.8.0
    - bashlex==0.16
    - black==22.3.0
    - bleach==3.3.0
    - blessings==1.7
    - bracex==2.2.1
    - cachetools==4.1.1
    - cffi==1.14.5
    - cfgv==3.2.0
    - chardet==3.0.4
    - cibuildwheel==2.3.1
    - click==8.0.0
    - cloudpickle==1.3.0
    - colorama==0.4.3
    - colorful==0.5.4
    - coverage==5.2.1
    - cryptography==3.4.6
    - cycler==0.10.0
    - distlib==0.3.1
    - docutils==0.16
    - filelock==3.0.12
    - flake8==3.8.3
    - flake8-bugbear==20.1.4
    - future==0.18.2
    - google-api-core==1.22.1
    - google-auth==1.20.1
    - google-auth-oauthlib==0.4.1
    - googleapis-common-protos==1.52.0
    - gpustat==0.6.0
    - GPUtil==1.4.0
    - grpcio==1.32.0
    - gymnasium==0.26.1
    - gymnasium-notices==0.0.1
    - hiredis==1.1.0
    - identify==1.4.28
    - idna==2.10
    - imagesize==1.2.0
    - importlib-metadata==4.12.0
    - iniconfig==1.0.1
    - isort==5.4.2
    - jeepney==0.6.0
    - Jinja2==2.11.2
    - jsonschema==3.2.0
    - keyring==22.2.0
    - kiwisolver==1.2.0
    - lazy-object-proxy==1.4.3
    - Markdown==3.2.2
    - MarkupSafe==1.1.1
    - matplotlib==3.3.1
    - mccabe==0.6.1
    - more-itertools==8.12.0
    - msgpack==1.0.0
    - multidict==4.7.6
    - mypy==0.812
    - mypy-extensions==0.4.3
    - nodeenv==1.4.0
    - numpy==1.19.5
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.1.0
    - opencensus==0.7.10
    - opencensus-context==0.1.1
    - packaging==20.4
    - pandas==1.1.0
    - pathspec==0.9.0
    - Pillow==7.2.0
    - pkginfo==1.7.0
    - platformdirs==2.4.1
    - plotly==4.9.0
    - pluggy==0.13.1
    - pre-commit==2.6.0
    - pre-commit-hooks==3.2.0
    - prometheus-client==0.8.0
    - protobuf==3.19.3
    - psutil==5.7.2
    - py==1.9.0
    - py-spy==0.3.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.6.0
    - pycparser==2.20
    - pyflakes==2.2.0
    - pyglet==1.5.0
    - Pygments==2.6.1
    - pyparsing==2.4.7
    - pyrsistent==0.16.0
    - pytest==6.0.1
    - pytest-cov==2.10.1
    - python-dateutil==2.8.1
    - pytz==2020.1
    - pywin32-ctypes==0.2.0
    - PyYAML==5.3.1
    - ray==1.13.0
    - readme-renderer==29.0
    - redis==3.5.3
    - regex==2020.7.14
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - requests-toolbelt==0.9.1
    - retrying==1.3.3
    - rfc3986==1.4.0
    - rsa==4.6
    - ruamel.yaml==0.16.10
    - ruamel.yaml.clib==0.2.0
    - scipy==1.5.2
    - SecretStorage==3.3.1
    - six==1.15.0
    - snowballstemmer==2.0.0
    - Sphinx==3.2.1
    - sphinx-autoapi==1.5.0
    - sphinx-autodoc-typehints==1.11.0
    - sphinx-rtd-theme==0.5.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - tabulate==0.8.7
    - tensorboard==2.6.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.7.0
    - tensorboardX==2.1
    - toml==0.10.1
    - tomli==1.2.3
    - tqdm==4.48.2
    - twine==3.3.0
    - typed-ast==1.4.1
    - typing-extensions==4.0.1
    - Unidecode==1.1.1
    - urllib3==1.25.10
    - virtualenv==20.0.31
    - webencodings==0.5.1
    - Werkzeug==1.0.1
    - wrapt==1.12.1
    - yarl==1.5.1
